FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

WORKDIR /app

# RUN apt-get update && apt-get install -y --no-install-recommends \
#     curl \
#     && rm -rf /var/lib/apt/lists/*


RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    gcc \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install dependencies
COPY TELEGRAM_BOT_API/requirements.txt .

RUN uv pip install --system uvicorn
RUN uv pip install --system --no-cache -r requirements.txt

# Copy shared package
COPY COMMON /app/COMMON

# Copy Telegram code
COPY TELEGRAM_BOT_API/ /app/

EXPOSE 8080

CMD ["./entrypoint_bot.sh"]

# # Give execution permission to the script inside its actual directory
# RUN chmod +x /app/TELEGRAM_BOT_API/entrypoint_bot.sh

# # Update CMD to point to the correct path
# CMD ["/app/TELEGRAM_BOT_API/entrypoint_bot.sh"]