FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

WORKDIR /app

# RUN apt-get update && apt-get install -y --no-install-recommends \
#     curl \
#     && rm -rf /var/lib/apt/lists/*


RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    gcc \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install dependencies
COPY FACEBOOK_BOT_API/requirements.txt .

RUN uv pip install --system uvicorn
RUN uv pip install --system --no-cache -r requirements.txt

# Copy shared package
COPY COMMON /app/COMMON

# Copy facebook code
COPY FACEBOOK_BOT_API/ /app/

EXPOSE 5000

CMD ["./entrypoint_facebook.sh"]