# Generated by Django 5.2.10 on 2026-03-22 17:05

import encrypted_model_fields.fields
import restaurants.models
import shortuuid.django_fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123456789', db_index=True, length=10, max_length=20, prefix='res', unique=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='restaurant.jpg', null=True, upload_to=restaurants.models.resturant_image_path)),
                ('bot_username', models.CharField(blank=True, max_length=100, null=True)),
                ('bot_token', encrypted_model_fields.fields.EncryptedCharField(null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('webhook_secret_token', models.CharField(blank=True, default=uuid.uuid4, help_text='X-Telegram-Bot-Api-Secret-Token', max_length=255, null=True)),
                ('is_bot_active', models.BooleanField(db_index=True, default=True)),
                ('is_accepting_orders', models.BooleanField(default=True)),
                ('kitchen_chat_id', models.BigIntegerField(blank=True, help_text='Telegram kitchen group chat ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
