# Generated by Django 5.2.10 on 2026-03-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='webhook_url',
        ),
    ]
