# Generated by Django 5.2.10 on 2026-03-26 11:46

import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurants.models.resturant_image_path),
        ),
    ]
