# Generated by Django 5.2.10 on 2026-03-27 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_image'),
        ('userAuths', '0002_remove_telegramuser_userauths_t_telegra_4ad56d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuths.telegramuser')),
            ],
            options={
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
