# Generated by Django 5.2.10 on 2026-04-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurantmembership'),
        ('userAuths', '0002_remove_telegramuser_userauths_t_telegra_4ad56d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmembership',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurantmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='userAuths.telegramuser'),
        ),
    ]
