# Generated by Django 5.2.10 on 2026-04-13 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurantmembership_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='average_preparation_time',
            field=models.PositiveIntegerField(default=30, help_text='Minutes'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram delivery group chat ID (if supports_delivery is True)', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_tables',
            field=models.PositiveSmallIntegerField(default=0, help_text='Amount of tables a restaurant has for dine-in orders'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service_mode',
            field=models.CharField(choices=[('dine_in', 'In-Restaurant Only'), ('delivery', 'Delivery Only'), ('both', 'Dine-in & Delivery')], db_index=True, default='dine_in', help_text='Primary service mode of the restaurant', max_length=20),
        ),
        migrations.CreateModel(
            name='RestaurantDeliveryOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_opening_hours', to='restaurants.restaurant')),
            ],
        ),
    ]
