# Generated by Django 5.2.10 on 2026-04-15 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_average_preparation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('vendor', 'Vendor')], default='restaurant', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantdeliveryopeninghours',
            name='day_of_week',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
