# Generated by Django 5.2.10 on 2026-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='service_mode',
            field=models.CharField(choices=[('dine_in', 'In-Restaurant Only'), ('delivery', 'Delivery Only'), ('both', 'Dine-in & Delivery')], db_index=True, help_text='Primary service mode of the restaurant', max_length=20),
        ),
    ]
