# Generated by Django 5.2.10 on 2026-04-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_restaurant_service_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('vendor', 'Vendor')], db_index=True, help_text='Type of business: Restaurant or Vendor', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='service_mode',
            field=models.CharField(choices=[('dine_in', 'In-Restaurant Only'), ('delivery', 'Delivery Only'), ('both', 'Dine-in & Delivery')], db_index=True, help_text='Primary service mode of the business', max_length=20),
        ),
    ]
