# Generated by Django 5.2.10 on 2026-04-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_restaurant_business_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurantdeliveryopeninghours',
            unique_together={('restaurant', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='restaurantdeliveryopeninghours',
            index=models.Index(fields=['restaurant', 'day_of_week'], name='restaurants_restaur_e00076_idx'),
        ),
    ]
