# Generated by Django 5.2.10 on 2026-04-28 10:02

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_restaurant_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_whatsapp_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether WhatsApp bot is active'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='WhatsApp Cloud API access token', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_business_account_id',
            field=models.CharField(blank=True, help_text='WhatsApp Business Account ID (WABA ID)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_business_phone',
            field=models.CharField(blank=True, help_text='WhatsApp business phone number (e.g., +2348123456789)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, help_text='WhatsApp Phone Number ID for sending messages', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_webhook_verified',
            field=models.BooleanField(default=False, help_text='Whether WhatsApp webhook has been verified'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_preparation_time',
            field=models.PositiveIntegerField(default=30, help_text='Minutes - How long food usually takes before it is ready'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram delivery group chat ID (if supports_delivery is True) OR WhatsApp delivery group ID', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='kitchen_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram kitchen group chat ID OR WhatsApp group ID', null=True),
        ),
    ]
