# Generated by Django 5.2.10 on 2026-05-04 18:29

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_restaurant_is_whatsapp_active_and_more'),
        ('userAuths', '0005_remove_authtoken_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DineInOTPSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, length=22, max_length=100, prefix='', unique=True)),
                ('table_number', models.PositiveSmallIntegerField()),
                ('waiter_telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('waiter_username', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for waiter'), ('verified', 'Customer verified'), ('expired', 'OTP expired'), ('cancelled', 'Cancelled by waiter')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuths.telegramuser')),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant', 'status'], name='restaurants_restaur_8795e9_idx'), models.Index(fields=['user', 'restaurant', 'status'], name='restaurants_user_id_11560b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('restaurant', 'otp_code'), name='unique_active_otp_per_restaurant')],
            },
        ),
    ]
