# Generated by Django 5.2.10 on 2026-05-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_dineinotpsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, help_text='Physical address of the restaurant', max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, help_text='City where the restaurant is located', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pick_up_address_id',
            field=models.CharField(blank=True, help_text='Terminal API address ID for delivery logistics', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.CharField(blank=True, help_text='State or region where the restaurant is located', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='kitchen_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram Dine-in kitchen group chat ID OR WhatsApp group ID', null=True),
        ),
    ]
