# Generated by Django 5.2.10 on 2026-05-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_restaurant_address_restaurant_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='payment_flow',
            field=models.CharField(blank=True, choices=[('postpay', 'Pay After Service (Order now, pay later)'), ('prepay', 'Pay Before Service (Pay now, kitchen prepares)')], help_text='Dine-in payment flow: Pay after service (traditional) or Pay before service (prepaid)', max_length=20, null=True),
        ),
    ]
