# Generated by Django 5.2.10 on 2026-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_restaurant_payment_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, help_text='Physical address of the restaurant', max_length=45, null=True),
        ),
    ]
