# Generated by Django 5.2.10 on 2026-05-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_alter_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='zipcode',
            field=models.CharField(blank=True, help_text="Postal code for the restaurant's location", max_length=20, null=True),
        ),
    ]
