# Generated by Django 5.2.10 on 2026-05-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_remove_restaurant_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='payment_flow',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('vendor', 'Vendor'), ('hotel', 'Hotel')], db_index=True, help_text='Type of business: Restaurant or Vendor', max_length=20),
        ),
    ]
