# Generated by Django 5.2.10 on 2026-05-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_remove_restaurant_payment_flow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('vendor', 'Vendor'), ('hotel', 'Hotel')], db_index=True, help_text='Type of business: Restaurant, Vendor, or Hotel', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram delivery group chat ID OR WhatsApp delivery group ID', null=True),
        ),
    ]
