# Generated by Django 5.2.10 on 2026-06-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_alter_restaurant_business_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantdeliveryopeninghours',
            name='is_closed',
        ),
    ]
