# Generated by Django 5.2.10 on 2026-06-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_remove_restaurantdeliveryopeninghours_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
