# Generated by Django 5.2.10 on 2026-06-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0022_restaurant_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='vendor_type',
            field=models.CharField(blank=True, choices=[('cooked_food', 'Cooked Food Vendor'), ('goods', 'Goods Vendor')], help_text='Only applies to vendors. Cooked food vendors have a 15km delivery limit.', max_length=20, null=True),
        ),
    ]
