# Generated by Django 5.2.10 on 2026-06-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0023_restaurant_vendor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='max_delivery_radius_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
