# Generated by Django 5.2.10 on 2026-06-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0024_alter_restaurant_max_delivery_radius_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_verified_name',
            field=models.CharField(blank=True, help_text='WhatsApp Bussiness Verified Name', max_length=255, null=True),
        ),
    ]
