# Generated by Django 5.2.10 on 2026-06-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0025_restaurant_whatsapp_verified_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner_telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_setup_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of WhatsApp onboarding after initial token exchange', max_length=20),
        ),
    ]
