# Generated by Django 5.2.10 on 2026-07-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0026_restaurant_owner_telegram_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hotel_service_type',
            field=models.CharField(blank=True, choices=[('dine_in', 'Restaurant (Dine-in)'), ('room_service', 'Room Service Only'), ('both', 'Both Restaurant & Room Service')], help_text='Only applies to hotels. Determines if the hotel has a restaurant, room service, or both.', max_length=20, null=True),
        ),
    ]
