# Generated by Django 5.2.10 on 2026-07-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0027_restaurant_hotel_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='max_tables',
            field=models.PositiveSmallIntegerField(default=10, help_text='Amount of tables a restaurant has for dine-in orders'),
        ),
    ]
