# Generated by Django 5.2.10 on 2026-07-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0028_alter_restaurant_max_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='service_mode',
            field=models.CharField(blank=True, choices=[('dine_in', 'In-Restaurant Only'), ('delivery', 'Delivery Only'), ('both', 'Dine-in & Delivery')], db_index=True, help_text='Primary service mode of the business', max_length=20, null=True),
        ),
    ]
