# Generated by Django 5.2.10 on 2026-07-11 17:15

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0029_alter_restaurant_service_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='hotel_service_type',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='facebook_app_scoped_id',
            field=models.CharField(blank=True, help_text='Optional App Scoped ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='facebook_page_access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Facebook Page Access Token', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='facebook_page_id',
            field=models.CharField(blank=True, help_text='Facebook Page ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_facebook_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether Facebook bot is active'),
        ),
    ]
