# Generated by Django 5.2.10 on 2026-07-14 14:06

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0030_remove_restaurant_hotel_service_type_and_more'),
        ('userAuths', '0005_remove_authtoken_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dineinotpsession',
            name='session_token',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, blank=True, db_index=True, help_text='session token for link sharing', length=35, max_length=35, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='dineinotpsession',
            name='session_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, length=22, max_length=255, prefix='', unique=True),
        ),
        migrations.CreateModel(
            name='DineInSessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Awaiting host approval'), ('accepted', 'Accepted by host'), ('declined', 'Declined by host'), ('removed', 'Removed after being accepted')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='restaurants.dineinotpsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuths.telegramuser')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'status'], name='restaurants_session_a00749_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('session', 'user'), name='unique_pending_request_per_user_per_session')],
            },
        ),
    ]
