# Generated by Django 5.2.10 on 2026-07-14 14:09

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0031_dineinotpsession_session_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dineinotpsession',
            name='session_token',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, blank=True, db_index=True, help_text='session token for link sharing', length=35, max_length=35, null=True, prefix='', unique=True),
        ),
    ]
