# Generated by Django 5.2.10 on 2026-07-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0032_alter_dineinotpsession_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='dineinotpsession',
            name='platform',
            field=models.CharField(blank=True, choices=[('whatsapp', 'Whatsapp App'), ('telegram', 'Telegram App')], help_text='The Host platform app', max_length=20, null=True),
        ),
    ]
