FROM ubuntu
RUN apt-get update
# Take test.txt from my current folder on my laptop and copy it into the image, inside a folder called copy_test_app/.”
# test.txt must exist on your laptop in the same folder as the Dockerfile.
# If copy_test_app/ does not exist inside the image, Docker creates it automatically.
COPY test.txt copy_test_app/ 
CMD ["echo", "testing the COPY"]