# Generated by Django 5.2.10 on 2026-03-22 17:14

import django.db.models.deletion
import orders.models
import shortuuid.django_fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('userAuths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123456789', length=10, max_length=20, prefix='', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123456789', length=10, max_length=13, prefix='ses', unique=True)),
                ('va_acct_number', models.CharField(blank=True, max_length=50, null=True)),
                ('va_bank', models.CharField(blank=True, max_length=50, null=True)),
                ('va_expiry', models.DateTimeField(blank=True, null=True)),
                ('merchant_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('None', 'None'), ('cash', 'CASH'), ('pos', 'POS'), ('dynamic_virtual_account', 'dynamic_virtual_account')], default='None', max_length=100)),
                ('expected_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_received', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('webhook_payload', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_in_progress', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_session', to='restaurants.restaurant')),
                ('telegram_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_session', to='userAuths.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=10, max_length=20, prefix='', unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notified_kitchen', models.BooleanField(default=False)),
                ('notified_user', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(max_length=255, null=True, unique=True)),
                ('removed_cart_items', models.JSONField(blank=True, default=list)),
                ('checkout_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_batches', to='orders.checkoutsession')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to='restaurants.restaurant')),
                ('telegram_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_batches', to='userAuths.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123456789', length=10, max_length=20, prefix='', unique=True)),
                ('title', models.CharField(default='Affordable meal', max_length=100, unique=True)),
                ('image', models.ImageField(default='product.jpg', upload_to=orders.models.product_image_path)),
                ('description', models.TextField(blank=True, default='This is the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('in_stock', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='orders.category')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_products', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderbatch')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('telegram_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='userAuths.telegramuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='product.jpg', upload_to=orders.models.product_image_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_images', to='orders.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['restaurant'], name='orders_cate_restaur_3c80d5_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['telegram_user', 'restaurant', 'is_active', 'date_created'], name='orders_chec_telegra_13431f_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('restaurant', 'telegram_user'), name='one_active_session_per_user'),
        ),
        migrations.AddIndex(
            model_name='orderbatch',
            index=models.Index(fields=['telegram_user', 'restaurant', 'checkout_session'], name='orders_orde_telegra_967468_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'date', 'restaurant'], name='orders_prod_categor_3d1a46_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbatchitem',
            index=models.Index(fields=['batch', 'product'], name='orders_orde_batch_i_f40972_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['product', 'telegram_user'], name='orders_cart_product_3e54af_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('telegram_user', 'product'), name='unique_telegram_user_product'),
        ),
    ]
