# Generated by Django 5.2.10 on 2026-04-09 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0005_alter_restaurantmembership_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbatch',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to='restaurants.restaurant'),
        ),
    ]
