# Generated by Django 5.2.10 on 2026-01-30 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('userAuths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='userAuths.telegramuser'),
        ),
        migrations.AddField(
            model_name='category',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='userAuths.telegramuser'),
        ),
        migrations.AddField(
            model_name='orderbatch',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_batches', to='userAuths.telegramuser'),
        ),
        migrations.AddField(
            model_name='orderbatchitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderbatch'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='orders.category'),
        ),
        migrations.AddField(
            model_name='orderbatchitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='orders.product'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_images', to='orders.product'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['telegram_user'], name='orders_cate_telegra_3968ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('telegram_user',), name='unique_telegram_user'),
        ),
        migrations.AddIndex(
            model_name='orderbatch',
            index=models.Index(fields=['telegram_user'], name='orders_orde_telegra_957d0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderbatch',
            constraint=models.UniqueConstraint(fields=('bid', 'telegram_user'), name='unique_telegram_user_bid'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='orders_prod_categor_56d6fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category',), name='unique_telegram_user_category'),
        ),
        migrations.AddIndex(
            model_name='orderbatchitem',
            index=models.Index(fields=['product'], name='orders_orde_product_bc53f1_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['product', 'telegram_user'], name='orders_cart_product_3e54af_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('telegram_user', 'product'), name='unique_telegram_user_product'),
        ),
    ]
