# Generated by Django 5.2.10 on 2026-04-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderbatch_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='dine_in_table_number',
            field=models.PositiveSmallIntegerField(default=5, help_text='Require customers to provide table number for dine-in orders'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='service_mode',
            field=models.CharField(choices=[('dine_in', 'In-Restaurant Only'), ('delivery', 'Delivery Only')], db_index=True, default='dine_in', help_text='Service mode for this checkout session', max_length=20),
        ),
    ]
