# Generated by Django 5.2.10 on 2026-01-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
