# Generated by Django 5.2.10 on 2026-01-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update',
            new_name='update_at',
        ),
    ]
