# Generated by Django 5.2.10 on 2026-04-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_checkoutsession_dine_in_table_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='dine_in_table_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Require customers to provide table number for dine-in orders', null=True),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='service_mode',
            field=models.CharField(choices=[('dine_in', 'In-Restaurant Only'), ('delivery', 'Delivery Only')], db_index=True, help_text='Service mode for this checkout session', max_length=20),
        ),
    ]
