# Generated by Django 5.2.10 on 2026-01-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_update_product_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='update_at',
        ),
    ]
