# Generated by Django 5.2.10 on 2026-04-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_checkoutsession_dine_in_table_number_and_more'),
        ('restaurants', '0010_alter_restaurantdeliveryopeninghours_unique_together_and_more'),
        ('userAuths', '0002_remove_telegramuser_userauths_t_telegra_4ad56d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checkoutsession',
            name='one_active_session_per_user',
        ),
        migrations.RemoveIndex(
            model_name='checkoutsession',
            name='orders_chec_telegra_13431f_idx',
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='delivery_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='delivery_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='delivery_landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['telegram_user', 'restaurant', 'is_active'], name='orders_chec_telegra_d2ab52_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('restaurant', 'telegram_user', 'service_mode'), name='one_active_session_per_user_per_mode'),
        ),
    ]
