# Generated by Django 5.2.10 on 2026-04-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_checkoutsession_one_active_session_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='prep_time_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Prep time for items in this category'),
        ),
    ]
