# Generated by Django 5.2.10 on 2026-01-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_product_updated_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_telegram_user_category',
        ),
    ]
