# Generated by Django 5.2.10 on 2026-04-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_category_prep_time_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_qty_per_order',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum quantity allowed per order (leave blank for unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='prep_day',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='prep days for items in this category', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='prep_time_minutes',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Prep time for items in this category', null=True),
        ),
    ]
