# Generated by Django 5.2.10 on 2026-01-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_product_unique_telegram_user_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('response_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderbatch',
            name='idempotency_key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderbatch',
            name='notified_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderbatch',
            name='notified_user',
            field=models.BooleanField(default=False),
        ),
    ]
