# Generated by Django 5.2.10 on 2026-04-26 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_category_max_qty_per_order_category_prep_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='prep_day',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='prep days for items in this category', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='prep_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Prep time for items in this category', null=True),
        ),
    ]
