# Generated by Django 5.2.10 on 2026-05-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_category_prep_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='platform',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('whatsapp', 'Whatsapp')], db_index=True, help_text='platform used for this checkout session', max_length=100, null=True),
        ),
    ]
