# Generated by Django 5.2.10 on 2026-02-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_idempotentrequest_orderbatch_idempotency_key_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdempotentRequest',
        ),
        migrations.RemoveIndex(
            model_name='orderbatchitem',
            name='orders_orde_product_bc53f1_idx',
        ),
        migrations.AddIndex(
            model_name='orderbatchitem',
            index=models.Index(fields=['batch', 'product'], name='orders_orde_batch_i_f40972_idx'),
        ),
    ]
