# Generated by Django 5.2.10 on 2026-02-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_delete_idempotentrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbatch',
            name='removed_cart_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
