# Generated by Django 5.2.10 on 2026-05-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_checkoutsession_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutsession',
            name='dine_in_table_number',
        ),
        migrations.AddField(
            model_name='orderbatch',
            name='dine_in_table_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Require customers to provide table number for dine-in orders', null=True),
        ),
        migrations.AddField(
            model_name='orderbatch',
            name='platform',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('whatsapp', 'Whatsapp')], db_index=True, help_text='platform used for this checkout session', max_length=100, null=True),
        ),
    ]
