# Generated by Django 5.2.10 on 2026-05-19 14:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_checkoutsession_dine_in_table_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='Weight in kg (optional)', max_digits=10),
        ),
    ]
