# Generated by Django 5.2.10 on 2026-02-23 20:27

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderbatch_removed_cart_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='res', unique=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_telegram_user',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='orders_cate_telegra_3968ec_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='telegram_user',
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='orders.restaurant'),
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_products', to='orders.restaurant'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['restaurant'], name='orders_cate_restaur_3c80d5_idx'),
        ),
    ]
