# Generated by Django 5.2.10 on 2026-02-23 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_restaurant_remove_category_unique_telegram_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.restaurant'),
        ),
    ]
