# Generated by Django 5.2.10 on 2026-05-31 12:42

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='room_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='session_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123456789', length=20, max_length=23, prefix='ses', unique=True),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='transaction_type',
            field=models.CharField(choices=[('cash', 'CASH'), ('pos', 'POS'), ('card', 'CARD'), ('transfer', 'Transfer')], max_length=100, null=True),
        ),
    ]
