# Generated by Django 5.2.10 on 2026-06-01 23:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_checkoutsession_room_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutsession',
            name='merchant_reference',
        ),
        migrations.RemoveField(
            model_name='checkoutsession',
            name='va_acct_number',
        ),
        migrations.RemoveField(
            model_name='checkoutsession',
            name='va_bank',
        ),
        migrations.RemoveField(
            model_name='checkoutsession',
            name='va_expiry',
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='expected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True),
        ),
    ]
