# Generated by Django 5.2.10 on 2026-02-28 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_category_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbatch',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to='orders.restaurant'),
        ),
    ]
