# Generated by Django 5.2.10 on 2026-06-02 00:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_checkoutsession_merchant_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='bank_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True),
        ),
    ]
