# Generated by Django 5.2.10 on 2026-03-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderbatch_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='kitchen_chat_id',
            field=models.CharField(blank=True, help_text='Telegram kitchen group chat ID', max_length=50, null=True),
        ),
    ]
