# Generated by Django 5.2.10 on 2026-03-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_restaurant_kitchen_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='kitchen_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram kitchen group chat ID', null=True),
        ),
    ]
