# Generated by Django 5.2.10 on 2026-06-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_checkoutsession_bank_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='bank_choice',
            field=models.CharField(blank=True, choices=[('opay', 'OPay'), ('palmpay', 'PalmPay'), ('vpay', 'Vpay'), ('moniepoint', 'Moniepoint')], max_length=100, null=True),
        ),
    ]
