# Generated by Django 5.2.10 on 2026-06-10 15:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_checkoutsession_bank_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True),
        ),
    ]
