# Generated by Django 5.2.10 on 2026-03-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_restaurant_kitchen_chat_id'),
        ('userAuths', '0003_remove_telegramuser_userauths_t_telegra_47716d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderbatch',
            name='unique_telegram_user_bid',
        ),
        migrations.RemoveIndex(
            model_name='orderbatch',
            name='orders_orde_telegra_957d0a_idx',
        ),
        migrations.AddIndex(
            model_name='orderbatch',
            index=models.Index(fields=['telegram_user', 'restaurant'], name='orders_orde_telegra_4dbe5e_idx'),
        ),
    ]
