# Generated by Django 5.2.10 on 2026-03-09 11:40

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_orderbatch_unique_telegram_user_bid_and_more'),
        ('userAuths', '0004_adminuser_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123456789', length=10, max_length=13, prefix='ses', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='orderbatch',
            name='orders_orde_telegra_4dbe5e_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123456789', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123456789', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123456789', length=10, max_length=20, prefix='res', unique=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_session', to='orders.restaurant'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_session', to='userAuths.telegramuser'),
        ),
        migrations.AddField(
            model_name='orderbatch',
            name='checkout_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_batches', to='orders.checkoutsession'),
        ),
        migrations.AddIndex(
            model_name='orderbatch',
            index=models.Index(fields=['telegram_user', 'restaurant', 'checkout_session'], name='orders_orde_telegra_967468_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['telegram_user', 'restaurant', 'is_active'], name='orders_chec_telegra_d2ab52_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('restaurant', 'telegram_user'), name='one_active_session_per_user'),
        ),
    ]
