# Generated by Django 5.2.10 on 2026-06-10 18:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_checkoutsession_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True),
        ),
    ]
