# Generated by Django 5.2.10 on 2026-03-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_checkoutsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='va_acct_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='va_bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='va_trans_reference',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
