# Generated by Django 5.2.10 on 2026-06-12 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_checkoutsession_delivery_fee_and_more'),
        ('restaurants', '0021_remove_restaurantdeliveryopeninghours_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='dine_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dine_session', to='restaurants.dineinotpsession'),
        ),
    ]
