# Generated by Django 5.2.10 on 2026-03-09 16:13

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_checkoutsession_va_acct_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutsession',
            name='va_trans_reference',
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='transaction_reference',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123456789', blank=True, length=20, max_length=24, null=True, prefix='REF-', unique=True),
        ),
    ]
