# Generated by Django 5.2.10 on 2026-07-02 13:18

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_checkoutsession_dine_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='session_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123456789', length=35, max_length=38, prefix='ses', unique=True),
        ),
    ]
