# Generated by Django 5.2.10 on 2026-03-09 16:22

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_checkoutsession_va_trans_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='transaction_reference',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123456789', length=20, max_length=24, null=True, prefix='REF-', unique=True),
        ),
    ]
