# Generated by Django 5.2.10 on 2026-07-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_checkoutsession_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutsession',
            name='total_price',
        ),
    ]
