# Generated by Django 5.2.10 on 2026-03-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_checkoutsession_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='transaction_reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
