# Generated by Django 5.2.10 on 2026-07-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_remove_checkoutsession_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('pending_cash', '⏳ Pending Cash'), ('pending_pos', '⏳ Pending POS')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderbatch',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('pending_cash', '⏳ Pending Cash'), ('pending_pos', '⏳ Pending POS')], default='unpaid', max_length=20),
        ),
    ]
