# Generated by Django 5.2.10 on 2026-07-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_checkoutsession_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutsession',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='waiter_for_payment',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
