# Generated by Django 5.2.10 on 2026-03-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_checkoutsession_transaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='va_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
