# Generated by Django 5.2.10 on 2026-07-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_remove_checkoutsession_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='transaction_type',
            field=models.CharField(choices=[('cash', 'CASH'), ('pos', 'POS'), ('card', 'CARD'), ('transfer', 'Transfer')], max_length=100, null=True),
        ),
    ]
