# Generated by Django 5.2.10 on 2026-03-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_checkoutsession_va_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='amount_paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='webhook_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
