# Generated by Django 5.2.10 on 2026-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_checkoutsession_amount_paid_checkoutsession_paid_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutsession',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='amount_received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='expected_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='transaction_type',
            field=models.CharField(choices=[('None', 'None'), ('cash', 'CASH'), ('pos', 'POS'), ('dynamic_virtual_account', 'dynamic_virtual_account')], default='None', max_length=100),
        ),
    ]
