# Generated by Django 5.2.10 on 2026-10-04 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_checkoutsession_payment_status_and_more'),
        ('restaurants', '0033_dineinotpsession_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='dine_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_session', to='restaurants.dineinotpsession'),
        ),
    ]
