# Generated by Django 5.2.10 on 2026-03-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_checkoutsession_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
