# Generated by Django 5.2.10 on 2026-03-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_checkoutsession_transaction_reference'),
        ('userAuths', '0004_adminuser_restaurant'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='checkoutsession',
            name='orders_chec_telegra_d2ab52_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='orders_prod_categor_56d6fa_idx',
        ),
        migrations.RemoveField(
            model_name='checkoutsession',
            name='transaction_reference',
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='merchant_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='orderbatch',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['telegram_user', 'restaurant', 'is_active', 'date_created'], name='orders_chec_telegra_13431f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'date', 'restaurant'], name='orders_prod_categor_3d1a46_idx'),
        ),
    ]
