# Generated by Django 5.2.10 on 2026-03-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_checkoutsession_orders_chec_telegra_d2ab52_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='merchant_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
