# Generated by Django 5.2.10 on 2026-03-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_checkoutsession_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
