# Generated by Django 5.2.10 on 2026-03-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_checkoutsession_transaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='payment_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
