# Generated by Django 5.2.10 on 2026-02-23 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_restaurant_remove_category_unique_telegram_user_and_more'),
        ('userAuths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_users', to='orders.restaurant'),
        ),
    ]
