# Generated by Django 5.2.10 on 2026-03-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telegramuser',
            name='userAuths_t_telegra_4ad56d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='telegramuser',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['telegram_id'], name='userAuths_t_telegra_47716d_idx'),
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='restaurant',
        ),
    ]
