# Generated by Django 5.2.10 on 2026-03-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderbatch_restaurant'),
        ('userAuths', '0002_telegramuser_restaurant'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telegramuser',
            name='userAuths_t_telegra_47716d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='telegramuser',
            unique_together={('telegram_id', 'restaurant')},
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['telegram_id', 'restaurant'], name='userAuths_t_telegra_4ad56d_idx'),
        ),
    ]
