# Generated by Django 5.2.10 on 2026-03-04 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_orderbatch_unique_telegram_user_bid_and_more'),
        ('userAuths', '0003_remove_telegramuser_userauths_t_telegra_47716d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_users', to='orders.restaurant'),
        ),
    ]
