# Generated by Django 5.2.10 on 2026-04-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuths', '0003_authtoken_telegramuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='used',
        ),
        migrations.AddField(
            model_name='authtoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
