# Generated by Django 5.2.10 on 2026-04-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuths', '0004_remove_authtoken_used_authtoken_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='table_number',
        ),
    ]
