# Generated by Django 5.2.10 on 2026-06-03 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0020_alter_restaurant_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('moniepoint', 'Moniepoint'), ('opay', 'Opay'), ('palmpay', 'Palmpay')], db_index=True, max_length=20)),
                ('terminal_identifier', models.CharField(help_text='Terminal serial number or merchant ID from the POS provider', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_configs', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'POS Configuration',
                'verbose_name_plural': 'POS Configurations',
                'indexes': [models.Index(fields=['restaurant', 'is_active'], name='payments_po_restaur_cc10f1_idx')],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'brand'), name='unique_restaurant_brand')],
            },
        ),
    ]
